1. Виконати набір вправ. Всі завдання виконати 2 способами:
а) з використанням універсальних функцій бібліотеки NumPy.
b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
с) для обох випадків підрахувати час виконання скрипту та
зробити висновки.

Варіант 6

Вправа 1. Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.
In [2] task_1()
5
Out[2] [[1 0 0 0 0]
[0 2 0 0 0]
[0 0 3 0 0]
[0 0 0 4 0]
[0 0 0 0 5]]

In [39]:
import numpy as np

def task_1():
    n = int(input())
    result = np.zeros((n, n), dtype=int)
    for i in range(n):
        result[i, i] = i + 1
    return result

print(task_1())

5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру
n×m, в якому в кожному рядку з номером r і в кожному стовпчику з
номером c стоять 0, а інші елементи дорівнюють 1.
In [2] task_3()
6 7 2 3
Out[2] [[0 0 0 0 0 0 0]
[0 1 1 0 1 1 0]
[0 0 0 0 0 0 0]
[0 1 1 0 1 1 0]
[0 0 0 0 0 0 0]
[0 1 1 0 1 1 0]]

In [40]:
import numpy as np

def task_3():
    n, m, r, c = map(int, input().split())
    result = np.ones((n, m), dtype=int)
    result[np.arange(0, n, r), :] = 0  
    result[:, np.arange(0, m, c)] = 0  
    return result

print(task_3())

6 7 2 3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


Вправа 4. Вводяться числа n і m. Вивести масив розміру n×m, в
якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0
до m–1, а всі інші елементи матриці дорівнюють 0.
In [2] task_4()
3 4
Out[2] [[0 1 2]
[0 0 0]
[0 0 0]
[0 0 0]]

In [41]:
import numpy as np

def task_4():
    n, m = map(int, input().split())
    result = np.zeros((m, n), dtype=int)
    result[0] = np.arange(n)
    return result

print(task_4())

3 4
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові
елементи на –1.
In [2] task_6()
3 4 0 9 7 0 6 0 4 0 3
Out[2] [-1 -1 0 -1 -1 0 -1 0 -1 0 -1]

In [42]:
import numpy as np

def task_6():
    array = np.array(list(map(int, input().split())))
    array[array != 0] = -1
    return array

print(task_6())

3 4 0 9 7 0 6 0 4 0 3
[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]


Вправа 10. Вводиться числа n i m. Створити масив випадкових
значень n×m і обчислити мінімальне, максимальне значення, середнє та
середньо квадратичне відхилення, округлене до 3 знаків після коми.
In [2] task_10()
4 5
Out [2] мінімум: 0.038
максимум: 0.946
середнє: 0.593
дисперсія: 0.302

In [43]:
import numpy as np

def task_10():
    n, m = map(int, input().split())
    array = np.random.rand(n, m)
    
    minimum = np.min(array)
    maximum = np.max(array)
    mean = np.mean(array)
    variance = np.var(array)
    std_deviation = np.sqrt(variance)
    
    return f"мінімум: {minimum:.3f}\nмаксимум: {maximum:.3f}\nсереднє: {mean:.3f}\nдисперсія: {variance:.3f}"

print(task_10())

4 5
мінімум: 0.173
максимум: 0.964
середнє: 0.469
дисперсія: 0.052


Вправа 12. Створити масив одиниць розміром n×n та створити в
ньому «рамку», що утворюється з 0.
In [2] task_12()
4
Out [2] [[0. 0. 0. 0.]
[0. 1. 1. 0.]
[0. 1. 1. 0.]
[0. 0. 0. 0.]]

In [44]:
import numpy as np

def task_12():
    n = int(input())
    array = np.ones((n, n))
    array[0:, 0] = 0
    array[0:, -1] = 0
    array[0, 0:] = 0
    array[-1, 0:] = 0
    return array

print(task_12())

4
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


Вправа 15. Заповнити парні стовпчикі матриці розміром n×n
одиницями, а непарні – нулями.
In [2] task_16()
5
Out [2] [[0 1 0 1 0]
[0 1 0 1 0]
[0 1 0 1 0]
[0 1 0 1 0]
[0 1 0 1 0]]

In [45]:
import numpy as np

def task_15():
    n = int(input())
    array = np.ones((n, n), dtype=int)
    array[:, ::2] = 0 
    return array

print(task_15())

5
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


Вправа 17. Заповнити вектор значеннями від 0 до n. Замінити
знаки для всіх значень, що менші за n/2 та більші за 3n/4 на
протилежні.
In [2] task_18()
10
Out [2] [ 0 -1 2 3 4 5 6 7 8 -9 -10]

In [46]:
import numpy as np

def task_17():
    n = int(input())
    vector = np.arange(n + 1)
    condition = (vector <= n/2) | (vector > 3*n/4)  
    vector[condition] *= -1  
    return vector

print(task_17())

10
[  0  -1  -2  -3  -4  -5   6   7  -8  -9 -10]


Вправа 18. Згенерувати вектор з n випадкових чисел в діапазоні
від 0 до 99. Визначити кількість унікальних чисел в послідовності.
In [2] task_19()
30
Out [2] В послідовності [ 5 77 15 21 8 44 58 77 6
49 35 35 25 3 51 65 73 81 67 78 85 68 40 77 58 1 10 9
59 13] - 26 унікальних чисел

In [47]:
import numpy as np

def task_18():
    n = int(input())
    vector = np.random.randint(0, 100, size=n)  
    unique_count = len(np.unique(vector)) 
    return f"В послідовності {vector} - {unique_count} унікальних чисел"

print(task_18())

30
В послідовності [ 7 82 48 26 88  5 37  8 27  9 75 44 63 11 80 51 82  7 41 56 67 51 30  1
 78 30 99 73 10 44] - 25 унікальних чисел


2. Розв’язати систему алгебраїчних рівнянь за допомогою
формул Крамера і виконати перевірку за допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose().

\begin{cases}
    x_1 + 5x_2 + 3x_3 - 4x_4 = 20 \\
    3x_1 + x_2 - 2x_3 = 9 \\
    5x_1 - 7x_2 + 10x_4 = -9 \\
    3x_2 - 5x_3 = 1
\end{cases}

In [48]:
import numpy as np

# Задання матриці коефіцієнтів A та вектора правих частин B
A = np.array([[1, 5, 3, -4],
              [3, 1, -2, 0],
              [5, -7, 0, 10],
              [0, 3, -5, 0]])

B = np.array([20, 9, -9, 1])

# Знаходимо визначник головної матриці Delta
Delta = np.linalg.det(A)

# Знаходимо визначники для матриць, утворених заміною стовпців відповідно до кожної змінної
Deltas = []
for i in range(A.shape[1]):
    A_i = A.copy()
    A_i[:, i] = B
    Deltas.append(np.linalg.det(A_i))

# Знаходимо розв'язки за формулами Крамера
x_kramer = [Deltas[i] / Delta for i in range(len(Deltas))]

# 1. Знаходження розв'язку за допомогою функції numpy.linalg.solve()
x_solve = np.linalg.solve(A, B)

# 2. Перевірка розв'язку за допомогою матричного множення та оберненої матриці
A_inv = np.linalg.inv(A)
x_inv = np.dot(A_inv, B)

# 3. Порівняння з розв'язками за допомогою формул Крамера
x_kramer = [Deltas[i] / Delta for i in range(len(Deltas))]

# Порівняння розв'язків
print("Розв'язок за допомогою numpy.linalg.solve():", x_solve)
print("Розв'язок за допомогою оберненої матриці:", x_inv)
print("Розв'язок за формулами Крамера:", x_kramer)

# Перевірка за допомогою numpy.allclose()
check_solve = np.allclose(x_solve, x_kramer)
check_inv = np.allclose(x_inv, x_kramer)

print("\nПеревірка розв'язку з numpy.linalg.solve() та формул Крамера:", check_solve)
print("Перевірка розв'язку з оберненою матрицею та формул Крамера:", check_inv)


Розв'язок за допомогою numpy.linalg.solve(): [ 3.  2.  1. -1.]
Розв'язок за допомогою оберненої матриці: [ 3.  2.  1. -1.]
Розв'язок за формулами Крамера: [2.9999999999999982, 2.0, 1.0000000000000007, -0.9999999999999991]

Перевірка розв'язку з numpy.linalg.solve() та формул Крамера: True
Перевірка розв'язку з оберненою матрицею та формул Крамера: True


3. Обчислити значення матричного виразу
а) з використанням універсальних функцій бібліотеки NumPy.
b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
с) для обох випадків підрахувати час виконання скрипту та
зробити висновок.
Порівняти всі рішення за допомогою функції numpy.allclose().


(A - B^2)(2A + B), 
де A = \begin{pmatrix}
5 & 2 & 0 \\
10 & 4 & 1 \\
7 & 3 & 2
\end{pmatrix}, 
B = \begin{pmatrix}
3 & 6 & -1 \\
-1 & -2 & 0 \\
2 & 1 & 3
\end{pmatrix}

In [49]:
import numpy as np
import time

# Задання матриць A і B
A = np.array([[5, 2, 0],
              [10, 4, 1],
              [7, 3, 2]])

B = np.array([[3, 6, -1],
              [-1, -2, 0],
              [2, 1, 3]])

# Обчислення значення матричного виразу з використанням універсальних функцій NumPy
start_time = time.time()
result_numpy = np.dot(A - np.square(B), 2 * A + B)
numpy_execution_time = time.time() - start_time

print("Результат з використанням універсальних функцій NumPy:")
print(result_numpy)
print("Час виконання скрипту (NumPy):", numpy_execution_time)

# Обчислення значення матричного виразу за допомогою ітеративних конструкцій
start_time = time.time()
result_iterative = np.zeros_like(A)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        result_iterative[i, j] = (A[i, j] - B[i, j]**2) * (2 * A[i, j] + B[i, j])
iterative_execution_time = time.time() - start_time

print("\nРезультат з використанням ітеративних конструкцій:")
print(result_iterative)
print("Час виконання скрипту (ітеративний):", iterative_execution_time)

# Порівняння результатів
print("\nЧи співпадають результати обчислень за допомогою NumPy та ітеративних конструкцій:")
print(np.allclose(result_numpy, result_iterative))

Результат з використанням універсальних функцій NumPy:
[[-714 -251  -71]
 [ 133   97   -2]
 [ -35   -7  -48]]
Час виконання скрипту (NumPy): 0.0010001659393310547

Результат з використанням ітеративних конструкцій:
[[ -52 -340    1]
 [ 171    0    2]
 [  48   14  -49]]
Час виконання скрипту (ітеративний): 0.0

Чи співпадають результати обчислень за допомогою NumPy та ітеративних конструкцій:
False
